# Project Euler - 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$arr,$result = $null
$upperlimit = 4000000
$arr = @(1,2)

do {
    $arr = $arr + ($arr[$arr.Count-1] + $arr[$arr.Count-2])
} while ($arr[$arr.Count-1] -le $upperlimit)

($arr | Where-Object {$_ % 2 -eq 0 }) | % { $result = $result + $_ }
$result
